

export interface ComponentConfig {
  tag: string;
  module?: string;
  triggers?: string[];
  docSource?: string; // 添加文档来源字段
  isHook?: boolean; // 是否为 Hooks 函数
  hookName?: string; // Hooks 函数名（如 useToast）
}

// 文档基础URL配置
export const DOC_BASE_URL = 'https://v2.wot-ui.cn/component/';
export const packageVersion = '1.0.0';

// 组件映射表 - 根据 zujian.ts 的 GlobalComponents 更新
export const COMPONENT_MAP: ComponentConfig[] = [
  { tag: "wd-action-sheet" },
  { tag: "wd-badge" },
  { tag: "wd-button" },
  { tag: "wd-calendar" },
  { tag: "wd-calendar-view"},
  { tag: "wd-card" },
  { tag: "wd-cell", docSource: "cell" },
  { tag: "wd-cell-group", docSource: "cell" },
  { tag: "wd-checkbox", docSource: "checkbox" },
  { tag: "wd-checkbox-group", docSource: "checkbox" },
  { tag: "wd-col", docSource: "layout" },
  { tag: "wd-cascader" },
  { tag: "wd-collapse", docSource: "collapse" },
  { tag: "wd-collapse-item", docSource: "collapse" },
  { tag: "wd-config-provider" },
  { tag: "wd-curtain" },
  { tag: "wd-datetime-picker" },
  { tag: "wd-datetime-picker-view" },
  { tag: "wd-divider" },
  { tag: "wd-drop-menu", docSource: "drop-menu" },
  { tag: "wd-drop-menu-item", docSource: "drop-menu" },
  { tag: "wd-grid", docSource: "grid" },
  { tag: "wd-grid-item", docSource: "grid" },
  { tag: "wd-icon" },
  { tag: "wd-img" },
  { tag: "wd-img-cropper"},
  { tag: "wd-input" },
  { tag: "wd-input-number" },
  { tag: "wd-loading" },
  { tag: "wd-loadmore" },
  { tag: "wd-dialog" },
  { tag: "wd-overlay" },
  { tag: "wd-notice-bar" },
  { tag: "wd-pagination" },
  { tag: "wd-picker" },
  { tag: "wd-picker-view"},
  { tag: "wd-popover" },
  { tag: "wd-popup" },
  { tag: "wd-progress" },
  { tag: "wd-radio", docSource: "radio" },
  { tag: "wd-radio-group", docSource: "radio" },
  { tag: "wd-rate" },
  { tag: "wd-resize" },
  { tag: "wd-row", docSource: "layout" },
  { tag: "wd-search" },
  { tag: "wd-select-picker" },
  { tag: "wd-slider" },
  { tag: "wd-sort-button" },
  { tag: "wd-empty" },
  { tag: "wd-step", docSource: "steps" },
  { tag: "wd-steps", docSource: "steps" },
  { tag: "wd-sticky", docSource: "sticky" },
  { tag: "wd-sticky-box", docSource: "sticky" },
  { tag: "wd-swipe-action" },
  { tag: "wd-switch" },
  { tag: "wd-tab", docSource: "tabs" },
  { tag: "wd-tabs", docSource: "tabs" },
  { tag: "wd-tag" },
  { tag: "wd-toast" },
  { tag: "wd-tooltip" },
  { tag: "wd-transition" },
  { tag: "wd-upload", docSource: "upload" },
  { tag: "wd-notify"},
  { tag: "wd-watermark" },
  { tag: "wd-circle" },
  { tag: "wd-swiper" },
  { tag: "wd-segmented" },
  { tag: "wd-tabbar", docSource: "tabbar" },
  { tag: "wd-tabbar-item", docSource: "tabbar" },
  { tag: "wd-navbar", docSource: "navbar" },
  { tag: "wd-navbar-capsule", docSource: "navbar" },
  { tag: "wd-table" },
  { tag: "wd-table-col", docSource: "table" },
  { tag: "wd-sidebar", docSource: "sidebar" },
  { tag: "wd-sidebar-item", docSource: "sidebar" },
  { tag: "wd-fab" },
  { tag: "wd-count-down" },
  { tag: "wd-keyboard" },
  { tag: "wd-gap" },
  { tag: "wd-password-input" },
  { tag: "wd-form", docSource: "form" },
  { tag: "wd-form-item", docSource: "form" },
  { tag: "wd-textarea" },
  { tag: "wd-video-preview" },
  { tag: "wd-backtop" },
  { tag: "wd-skeleton" },
  { tag: "wd-index-bar" },
  { tag: "wd-text" },
  { tag: "wd-count-to" },
  { tag: "wd-floating-panel" },
  { tag: "wd-signature" },
  { tag: "wd-root-portal" },
  { tag: "wd-tour" },
  { tag: "wd-avatar", docSource: "avatar" },
  { tag: "wd-avatar-group", docSource: "avatar" },
  { tag: "wd-image-preview" },
  { tag: "wd-slide-verify" },
  // Hooks 函数配置
  { tag: "use-toast", isHook: true, hookName: "useToast", docSource: "use-toast" },
  { tag: "use-upload", isHook: true, hookName: "useUpload", docSource: "use-upload" },
  { tag: "use-notify", isHook: true, hookName: "useNotify", docSource: "use-notify" },
  { tag: "use-config-provider", isHook: true, hookName: "useConfigProvider", docSource: "use-config-provider" },
  { tag: "use-count-down", isHook: true, hookName: "useCountDown", docSource: "use-count-down" },
  { tag: "use-message", isHook: true, hookName: "useMessage", docSource: "use-message" },
];